### ISSUE TITLE
Use case document needs restructuring

### ISSUE THREAD

**Issue by 6a6d74** [opengeospatial/weather-on-the-web#13]
I think you need another bit of structure 

https://github.com/opengeospatial/weather-on-the-web/blob/master/use-cases/use-cases.md#1-abstract

[BTW - this is a test ISSUE]

**Comment by RichCarne** [comment]
- [ ] Separate out uses cases, change use-cases.md to readme.md
- [ ] Remove deliverable section, move to readme.md in Root
- [ ] Update wiki to reflect new approach to use cases
- [ ] Add a use case template to the use case folder

**Comment by RichCarne** [comment]
Made required adjustments to repo structure, and created new pull request for first use case.
