### ISSUE TITLE
Design Principles

### ISSUE THREAD

**Issue by RichCarne** [opengeospatial/weather-on-the-web#23]
We should store the range of design principles that we agree on, such as adhering to WFS 3.0 and utilising the OpenAPI specification.

**Comment by chris-little** [comment]
Rich, Pete,

I propose that the [design principles ](https://github.com/opengeospatial/OGC-Web-API-Guidelines )now developed by OGC for OpenAPI based on the WFS3.0 experinece are the best starting point.

We do need to augment those 'core principles' with our specific needs for WotW
